### PR TITLE
Add homepage hero image

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Make the homepage hero a strip--image.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8019/](http://0.0.0.0:8019/))
- Check that the hero has a background image

## Issue / Card
Fixes https://github.com/canonical-websites/community.ubuntu.com/issues/6

### CODE REVIEW

**Comment by anthonydillon** [comment]
I agree the banner doesn't look great but it's up to design to provide a replacement. 

The idea of this is to replicate the live site without requiring any content.

**Comment by barrymcgee** [comment]
@kwm14 @spencerbygraves Can either of you help here?

**Comment by spencerbygraves** [comment]
Is there a demo link?

**Comment by barrymcgee** [comment]
@spencerbygraves Demo: http://community.ubuntu.com-add-homepage-hero-image.demo.haus

**Comment by spencerbygraves** [comment]
Ok, I see the problem. I'll have to try and find the original photo, or something to replace it.

**Comment by spencerbygraves** [comment]
Waiting for a response from Thibault on community images.

**Comment by anthonydillon** [comment]
Closing this PR to leave the hero without an image as there is no image provided.

**Pull request closed without merging**
